spring:
#  redis:
#    host: 192.168.2.44
#    port: 7546
#    password: XXXXXXX
#    lettuce:
#      pool:
#        max-total: 100      #    最大连接数
#        max-active: 200
#        min-idle: 20        #   最小空闲连接数
#        max-idle: 200
#        max-wait-millis: 10000   #   当池内没有可用的连接时，最大等待时间

  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8015
  servlet:
    context-path: /stores


