package com.onlinetea.prower.constants;

public interface Constants {

  /** 测试用数据，模拟cmdb */
  String CMDBDATA =
      "{\n"
          + "    \"totalRecords\": -1,\n"
          + "    \"dataList\": [\n"
          + "        {\n"
          + "            \"id\": \"6305e3270928310cb7a288d4\",\n"
          + "            \"tenantId\": \"e10adc3949ba59abbe56e057f20f88dd\",\n"
          + "            \"classCode\": \"BladeServer\",\n"
          + "            \"className\": \"刀片服务器\",\n"
          + "            \"outerObjectId\": null,\n"
          + "            \"objectVersion\": 1,\n"
          + "            \"state\": \"APPLY\",\n"
          + "            \"createTime\": \"2022-08-24 16:36:55\",\n"
          + "            \"updateTime\": \"2022-08-24 16:36:55\",\n"
          + "            \"sources\": [\n"
          + "                \"user\"\n"
          + "            ],\n"
          + "            \"tags\": null,\n"
          + "            \"resOwners\": [\n"
          + "                \"CMDB\",\n"
          + "                \"AUTOMATION\",\n"
          + "                \"NETWORK\",\n"
          + "                \"MONITOR\"\n"
          + "            ],\n"
          + "            \"name\": \"LHR测试数据\",\n"
          + "            \"bladeserver_brand\": \"huawei\",\n"
          + "            \"model\": \"DP1066\",\n"
          + "            \"mt_model\": \"M1066\",\n"
          + "            \"serial_number\": \"TM1066DP1066\",\n"
          + "            \"os_ip\": \"172.23.23.23\",\n"
          + "            \"device_model\": null,\n"
          + "            \"cpu_phys_num\": 8,\n"
          + "            \"memory_size\": \"2048\",\n"
          + "            \"cpu_model\": \"DP1066\",\n"
          + "            \"monitor_enabled\": \"false\",\n"
          + "            \"manage_account\": \"admin\",\n"
          + "            \"manage_password\": \">>>48ab8c44LtOfMXHbI7Hvsmzw/XBoYGnxkO8iP5iZdKRtSMXzYMY=<<<\",\n"
          + "            \"manager_nopass\": \"true\",\n"
          + "            \"cq_pzlxmc\": \"刀片服务测试1\",\n"
          + "            \"cq_bzqc\": \"测试用刀片服务1号\",\n"
          + "            \"cq_jc\": \"测刀1\",\n"
          + "            \"cq_cjsj\": \"2022-08-24T08:25:48.000+00:00\",\n"
          + "            \"cq_bz\": \"测刀1\",\n"
          + "            \"cq_sswl\": \"外网IPv6\",\n"
          + "            \"cq_ccxlh\": \"DP1066CC1066\",\n"
          + "            \"cq_swid\": \"DP1066\",\n"
          + "            \"cq_sbzt\": \"库存\",\n"
          + "            \"cq_tyrq\": \"2022-08-24T08:26:21.000+00:00\",\n"
          + "            \"cq_sctyrq\": \"2022-08-24T08:26:24.000+00:00\",\n"
          + "            \"cq_zzgj\": \"德国\",\n"
          + "            \"cq_zzsmc\": \"德国专业造刀100年\",\n"
          + "            \"cq_ppmc\": \"专造刀\",\n"
          + "            \"cq_xhmc\": \"DP1066T\",\n"
          + "            \"cq_yxdwmc_1\": \"专业测试刀片100年\",\n"
          + "            \"cq_sftbgerp_2\": \"是\",\n"
          + "            \"cq_azdd\": \"专业安装100年\",\n"
          + "            \"cq_lyrq\": \"2022-08-24T08:27:31.000+00:00\",\n"
          + "            \"cq_lyrlxfs\": \"17761718305\",\n"
          + "            \"cq_lydwmc_1\": \"专业领取100年\",\n"
          + "            \"cq_ywbmmc\": \"专业运维100年\",\n"
          + "            \"cq_ywzrr\": \"专业级责任人\",\n"
          + "            \"cq_aqbabh\": \"TAQ100DP1066\",\n"
          + "            \"cq_gcqy\": \"专业工厂100年\",\n"
          + "            \"cq_sybgbm\": \"专业保管100年\",\n"
          + "            \"cq_swglbm\": \"专业实物管理100年\",\n"
          + "            \"cq_sbbdfs\": \"购买\",\n"
          + "            \"cq_sbzjfs\": \"赊账\",\n"
          + "            \"cq_erpzcbm\": \"ERP100DP1066\",\n"
          + "            \"cq_erpsbtzbm\": \"ERP100DP1066MB\",\n"
          + "            \"cq_whgcxsmc\": \"专业维护100年\",\n"
          + "            \"cq_zzslxdh\": \"17761718305\",\n"
          + "            \"cq_xmmc\": \"测试用刀片1066\",\n"
          + "            \"cq_ccrq\": \"2022-08-24T08:30:12.000+00:00\",\n"
          + "            \"cq_cgrq\": \"2022-08-24T08:30:15.000+00:00\",\n"
          + "            \"cq_jg_1\": \"专业机柜\",\n"
          + "            \"cq_jxzt_1\": \"绝对安全\",\n"
          + "            \"cq_sbqsgd\": \"100\",\n"
          + "            \"cq_sbzzgd\": \"500\",\n"
          + "            \"cq_dyxx\": \"专业电源不会断\",\n"
          + "            \"cq_macdz_2\": \"147F258G369H\",\n"
          + "            \"cq_ipdz\": \"172.14.14.141\",\n"
          + "            \"cq_cpuxx\": \"爆炸型I6\",\n"
          + "            \"cq_ncxx\": \"最硬核内存\",\n"
          + "            \"cq_pzxid\": \"4A55B5A3-1F93-456F-8605-706E090F86F5-05991\",\n"
          + "            \"cq_pzlxid\": \"T10102\",\n"
          + "            \"cq_sfycsm\": \"80002\"\n"
          + "        },\n"
          +"             {\n"
          + "            \"id\": \"6305e3270928310cb7a288d4\",\n"
          + "            \"tenantId\": \"e10adc3949ba59abbe56e057f20f88dd\",\n"
          + "            \"classCode\": \"BladeServer\",\n"
          + "            \"className\": \"刀片服务器\",\n"
          + "            \"outerObjectId\": null,\n"
          + "            \"objectVersion\": 1,\n"
          + "            \"state\": \"APPLY\",\n"
          + "            \"createTime\": \"2022-08-24 16:36:55\",\n"
          + "            \"updateTime\": \"2022-08-24 16:36:55\",\n"
          + "            \"sources\": [\n"
          + "                \"user\"\n"
          + "            ],\n"
          + "            \"tags\": null,\n"
          + "            \"resOwners\": [\n"
          + "                \"CMDB\",\n"
          + "                \"AUTOMATION\",\n"
          + "                \"NETWORK\",\n"
          + "                \"MONITOR\"\n"
          + "            ],\n"
          + "            \"name\": \"LHR测试数据-2\",\n"
          + "            \"bladeserver_brand\": \"huawei\",\n"
          + "            \"model\": \"DP1066\",\n"
          + "            \"mt_model\": \"M1066\",\n"
          + "            \"serial_number\": \"TM1066DP1066\",\n"
          + "            \"os_ip\": \"172.23.23.23\",\n"
          + "            \"device_model\": null,\n"
          + "            \"cpu_phys_num\": 8,\n"
          + "            \"memory_size\": \"2048\",\n"
          + "            \"cpu_model\": \"DP1066\",\n"
          + "            \"monitor_enabled\": \"false\",\n"
          + "            \"manage_account\": \"admin\",\n"
          + "            \"manage_password\": \">>>48ab8c44LtOfMXHbI7Hvsmzw/XBoYGnxkO8iP5iZdKRtSMXzYMY=<<<\",\n"
          + "            \"manager_nopass\": \"true\",\n"
          + "            \"cq_pzlxmc\": \"刀片服务测试1\",\n"
          + "            \"cq_bzqc\": \"测试用刀片服务2号\",\n"
          + "            \"cq_jc\": \"测刀1\",\n"
          + "            \"cq_cjsj\": \"2022-08-24T08:25:48.000+00:00\",\n"
          + "            \"cq_bz\": \"测刀1\",\n"
          + "            \"cq_sswl\": \"外网IPv6\",\n"
          + "            \"cq_ccxlh\": \"DP1066CC1067\",\n"
          + "            \"cq_swid\": \"DP1066\",\n"
          + "            \"cq_sbzt\": \"库存\",\n"
          + "            \"cq_tyrq\": \"2022-08-24T08:26:21.000+00:00\",\n"
          + "            \"cq_sctyrq\": \"2022-08-24T08:26:24.000+00:00\",\n"
          + "            \"cq_zzgj\": \"德国\",\n"
          + "            \"cq_zzsmc\": \"德国专业造刀100年\",\n"
          + "            \"cq_ppmc\": \"专造刀\",\n"
          + "            \"cq_xhmc\": \"DP1066T\",\n"
          + "            \"cq_yxdwmc_1\": \"专业测试刀片100年\",\n"
          + "            \"cq_sftbgerp_2\": \"是\",\n"
          + "            \"cq_azdd\": \"专业安装100年\",\n"
          + "            \"cq_lyrq\": \"2022-08-24T08:27:31.000+00:00\",\n"
          + "            \"cq_lyrlxfs\": \"17761718305\",\n"
          + "            \"cq_lydwmc_1\": \"专业领取100年\",\n"
          + "            \"cq_ywbmmc\": \"专业运维100年\",\n"
          + "            \"cq_ywzrr\": \"专业级责任人\",\n"
          + "            \"cq_aqbabh\": \"TAQ100DP1066\",\n"
          + "            \"cq_gcqy\": \"专业工厂100年\",\n"
          + "            \"cq_sybgbm\": \"专业保管100年\",\n"
          + "            \"cq_swglbm\": \"专业实物管理100年\",\n"
          + "            \"cq_sbbdfs\": \"购买\",\n"
          + "            \"cq_sbzjfs\": \"赊账\",\n"
          + "            \"cq_erpzcbm\": \"ERP100DP1066\",\n"
          + "            \"cq_erpsbtzbm\": \"ERP100DP1066MB\",\n"
          + "            \"cq_whgcxsmc\": \"专业维护100年\",\n"
          + "            \"cq_zzslxdh\": \"17761718305\",\n"
          + "            \"cq_xmmc\": \"测试用刀片1066\",\n"
          + "            \"cq_ccrq\": \"2022-08-24T08:30:12.000+00:00\",\n"
          + "            \"cq_cgrq\": \"2022-08-24T08:30:15.000+00:00\",\n"
          + "            \"cq_jg_1\": \"专业机柜\",\n"
          + "            \"cq_jxzt_1\": \"绝对安全\",\n"
          + "            \"cq_sbqsgd\": \"100\",\n"
          + "            \"cq_sbzzgd\": \"500\",\n"
          + "            \"cq_dyxx\": \"专业电源不会断\",\n"
          + "            \"cq_macdz_2\": \"147F258G369H\",\n"
          + "            \"cq_ipdz\": \"172.14.14.141\",\n"
          + "            \"cq_cpuxx\": \"爆炸型I6\",\n"
          + "            \"cq_ncxx\": \"最硬核内存\",\n"
          + "            \"cq_pzxid\": \"4A55B5A3-1F93-456F-8605-706E090F86F5-05992\",\n"
          + "            \"cq_pzlxid\": \"T10103\",\n"
          + "            \"cq_sfycsm\": \"80002\"\n"
          + "        }\n"
          + "    ],\n"
          + "    \"empty\": false\n"
          + "}";

  /** 测试用数据，模拟I6000 */
  String I6OOODATA =
      "{\n"
          + "    \"successful\": \"true\",\n"
          + "    \"resultValue\": {\n"
          + "        \"items\": [\n"
          + "            {\n"
          + "                \"RN\": 1,\n"
          + "                \"GROUP_IDX\": 1,\n"
          + "                \"CI_NAME\": \"CISCO-460-刀片机-113\",\n"
          + "                \"CITYPE_NAME\": \"刀片机\",\n"
          + "                \"CI_ID\": \"4A55B5A3-1F93-456F-8605-706E090F86F5-05991\",\n"
          + "                \"CITYPE_ID\": \"T10102\",\n"
          + "                \"CITYPE\": \"T10102\",\n"
          + "                \"BASE_CITYPE_NAME\": \"刀片机\",\n"
          + "                \"RUN_CORP_CODE\": \"I6000新运行单位01\",\n"
          + "                \"BEBER\": \"40004304-01\",\n"
          + "                \"RCVD_CORP\": \"I6000领用单位01\",\n"
          + "                \"RCVD_USER\": \"I6000领用USER01\",\n"
          + "                \"NETWORK\": \"40002001\",\n"
          + "                \"MADE_COUNTRY\": \"I6000制造国家01\",\n"
          + "                \"RELEASE_NO\": \"I6000DP10600-01\",\n"
          + "                \"POWER_INFO\": \"I6000电源信息01\",\n"
          + "                \"ATTR_UNIT_LIST\": {\n"
          + "                    \"TEST001_10\": \"MHz\",\n"
          + "                    \"HARDDISK_VOLUME\": \"Byte\",\n"
          + "                    \"FILE_SYS_SIZE\": \"Byte\",\n"
          + "                    \"MEMORY_SIZE\": \"Byte\",\n"
          + "                    \"SWAPMEMSIZE\": \"Byte\",\n"
          + "                    \"VMEMORY_SIZE\": \"Byte\"\n"
          + "                },\n"
          + "                \"BEBER_NAME\": \"省公司\",\n"
          + "                \"NETWORK_NAME\": \"内网\"\n"
          + "            },\n"
          + "            {\n"
          + "                \"RN\": 2,\n"
          + "                \"GROUP_IDX\": 1,\n"
          + "                \"CI_NAME\": \"CISCO-460-刀片机-114\",\n"
          + "                \"CITYPE_NAME\": \"刀片机\",\n"
          + "                \"CI_ID\": \"4A55B5A3-1F93-456F-8605-706E090F86F5-05992\",\n"
          + "                \"CITYPE_ID\": \"T10103\",\n"
          + "                \"CITYPE\": \"T10103\",\n"
          + "                \"BASE_CITYPE_NAME\": \"刀片机\",\n"
          + "                \"RUN_CORP_CODE\": \"I6000新运行单位02\",\n"
          + "                \"BEBER\": \"40004304-02\",\n"
          + "                \"RCVD_CORP\": \"I6000领用单位02\",\n"
          + "                \"RCVD_USER\": \"I6000领用USER02\",\n"
          + "                \"NETWORK\": \"40002001\",\n"
          + "                \"MADE_COUNTRY\": \"I6000制造国家-2\",\n"
          + "                \"RELEASE_NO\": \"I6000DP10600-2\",\n"
          + "                \"POWER_INFO\": \"I6000电源信息-2\",\n"
          + "                \"ATTR_UNIT_LIST\": {\n"
          + "                    \"TEST001_10\": \"MHz\",\n"
          + "                    \"HARDDISK_VOLUME\": \"Byte\",\n"
          + "                    \"FILE_SYS_SIZE\": \"Byte\",\n"
          + "                    \"MEMORY_SIZE\": \"Byte\",\n"
          + "                    \"SWAPMEMSIZE\": \"Byte\",\n"
          + "                    \"VMEMORY_SIZE\": \"Byte\"\n"
          + "                },\n"
          + "                \"BEBER_NAME\": \"省公司\",\n"
          + "                \"NETWORK_NAME\": \"内网\"\n"
          + "            },\n"
          + "            {\n"
          + "                \"RN\": 7,\n"
          + "                \"GROUP_IDX\": 1,\n"
          + "                \"CI_NAME\": \"新建-CISCO-HS22-刀片机-51\",\n"
          + "                \"CITYPE_NAME\": \"刀片机\",\n"
          + "                \"CI_ID\": \"4F345B83-C1F8-4897-B0D9-63666C26212F-01278\",\n"
          + "                \"CITYPE_ID\": \"T10102\",\n"
          + "                \"CITYPE\": \"T10102\",\n"
          + "                \"BASE_CITYPE_NAME\": \"刀片机\",\n"
          + "                \"RUN_CORP_CODE\": \"新建-RN7领用单位\",\n"
          + "                \"BEBER\": \"40004303-07\",\n"
          + "                \"RCVD_CORP\": \"新建-I6000领用单位07\",\n"
          + "                \"RCVD_USER\": \"新建-I6000领用USER07\",\n"
          + "                \"NETWORK\": \"40002003\",\n"
          + "                \"ATTR_UNIT_LIST\": {\n"
          + "                    \"TEST001_10\": \"MHz\",\n"
          + "                    \"HARDDISK_VOLUME\": \"Byte\",\n"
          + "                    \"FILE_SYS_SIZE\": \"Byte\",\n"
          + "                    \"MEMORY_SIZE\": \"Byte\",\n"
          + "                    \"SWAPMEMSIZE\": \"Byte\",\n"
          + "                    \"VMEMORY_SIZE\": \"Byte\"\n"
          + "                },\n"
          + "                \"BEBER_NAME\": \"省公司\",\n"
          + "                \"NETWORK_NAME\": \"局域网\"\n"
          + "            },\n"
          + "            {\n"
          + "                \"RN\": 8,\n"
          + "                \"GROUP_IDX\": 1,\n"
          + "                \"CI_NAME\": \"CISCO-HS22-刀片机-86\",\n"
          + "                \"CITYPE_NAME\": \"刀片机\",\n"
          + "                \"CI_ID\": \"4F345B83-C1F8-4897-B0D9-63666C26212F-01281\",\n"
          + "                \"CITYPE_ID\": \"T10102\",\n"
          + "                \"CITYPE\": \"T10102\",\n"
          + "                \"BASE_CITYPE_NAME\": \"刀片机\",\n"
          + "                \"RUN_CORP_CODE\": \"新建-RN8领用单位\",\n"
          + "                \"BEBER\": \"新建-40004303-08\",\n"
          + "                \"RCVD_CORP\": \"新建-I6000领用单位08\",\n"
          + "                \"RCVD_USER\": \"新建-I6000领用USER08\",\n"
          + "                \"MADE_COUNTRY\": \"德国制造-R8\",\n"
          + "                \"NETWORK\": \"40002003\",\n"
          + "                \"ATTR_UNIT_LIST\": {\n"
          + "                    \"TEST001_10\": \"MHz\",\n"
          + "                    \"HARDDISK_VOLUME\": \"Byte\",\n"
          + "                    \"FILE_SYS_SIZE\": \"Byte\",\n"
          + "                    \"MEMORY_SIZE\": \"Byte\",\n"
          + "                    \"SWAPMEMSIZE\": \"Byte\",\n"
          + "                    \"VMEMORY_SIZE\": \"Byte\"\n"
          + "                },\n"
          + "                \"BEBER_NAME\": \"省公司\",\n"
          + "                \"NETWORK_NAME\": \"局域网\"\n"
          + "            },\n"
          + "            {\n"
          + "                \"RN\": 9,\n"
          + "                \"GROUP_IDX\": 1,\n"
          + "                \"CI_NAME\": \"DELL-POWEREDGE M610-刀片机-30\",\n"
          + "                \"CITYPE_NAME\": \"刀片机\",\n"
          + "                \"CI_ID\": \"1390D4B8-920B-49B4-B567-8D850C57A765-24604\",\n"
          + "                \"CITYPE_ID\": \"T10102\",\n"
          + "                \"CITYPE\": \"T10102\",\n"
          + "                \"BASE_CITYPE_NAME\": \"刀片机\",\n"
          + "                \"RUN_CORP_CODE\": \"新建-RN9领用单位\",\n"
          + "                \"BEBER\": \"新建-BEBER-09\",\n"
          + "                \"MADE_COUNTRY\": \"法国制造-R9\",\n"
          + "                \"RCVD_CORP\": \"新建-I6000领用单位09\",\n"
          + "                \"RCVD_USER\": \"新建-I6000领用USER09\",\n"
          + "                \"NETWORK\": \"40002004\",\n"
          + "                \"ATTR_UNIT_LIST\": {\n"
          + "                    \"TEST001_10\": \"MHz\",\n"
          + "                    \"HARDDISK_VOLUME\": \"Byte\",\n"
          + "                    \"FILE_SYS_SIZE\": \"Byte\",\n"
          + "                    \"MEMORY_SIZE\": \"Byte\",\n"
          + "                    \"SWAPMEMSIZE\": \"Byte\",\n"
          + "                    \"VMEMORY_SIZE\": \"Byte\"\n"
          + "                },\n"
          + "                \"BEBER_NAME\": \"省公司\",\n"
          + "                \"NETWORK_NAME\": \"未联网\"\n"
          + "            },\n"
          + "            {\n"
          + "                \"RN\": 10,\n"
          + "                \"GROUP_IDX\": 1,\n"
          + "                \"CI_NAME\": \"DELL-POWEREDGE M610-刀片机-47\",\n"
          + "                \"CITYPE_NAME\": \"刀片机\",\n"
          + "                \"CI_ID\": \"1390D4B8-920B-49B4-B567-8D850C57A765-24602\",\n"
          + "                \"CITYPE_ID\": \"T10102\",\n"
          + "                \"CITYPE\": \"T10102\",\n"
          + "                \"BASE_CITYPE_NAME\": \"刀片机\",\n"
          + "                \"RUN_CORP_CODE\": \"新建-RN10领用单位\",\n"
          + "                \"BEBER\": \"新建-BEBER-10\",\n"
          + "                \"MADE_COUNTRY\": \"新建-苯基涅制造-RN10\",\n"
          + "                \"RCVD_CORP\": \"新建-I6000领用单位10\",\n"
          + "                \"RCVD_USER\": \"新建-I6000领用USER10\",\n"
          + "                \"NETWORK\": \"40002004\",\n"
          + "                \"ATTR_UNIT_LIST\": {\n"
          + "                    \"TEST001_10\": \"MHz\",\n"
          + "                    \"HARDDISK_VOLUME\": \"Byte\",\n"
          + "                    \"FILE_SYS_SIZE\": \"Byte\",\n"
          + "                    \"MEMORY_SIZE\": \"Byte\",\n"
          + "                    \"SWAPMEMSIZE\": \"Byte\",\n"
          + "                    \"VMEMORY_SIZE\": \"Byte\"\n"
          + "                },\n"
          + "                \"BEBER_NAME\": \"省公司\",\n"
          + "                \"NETWORK_NAME\": \"未联网\"\n"
          + "            }\n"
          + "        ],\n"
          + "        \"itemCount\": 326\n"
          + "    },\n"
          + "    \"resultHint\": \"\"\n"
          + "}";
}
